export const ROBOFRIENDS_REQUEST: string = "ROBOFRIENDS_REQUEST";
export const ROBOFRIENDS_REQUEST_SUCCESS: string = "ROBOFRIENDS_REQUEST_SUCCESS";
export const ROBOFRIENDS_REQUEST_FAIL: string = "ROBOFRIENDS_REQUEST_FAIL";
