export const ROBOFRIENDS_REQUEST = "ROBOFRIENDS_REQUEST";
export const ROBOFRIENDS_REQUEST_SUCCESS = "ROBOFRIENDS_REQUEST_SUCCESS";
export const ROBOFRIENDS_REQUEST_FAIL = "ROBOFRIENDS_REQUEST_FAIL";
